version: "3.9"

services:
  short_url:
    build: ./shortURL
    container_name: shortURL
    ports:
      - "5000:5000"

  image_metadata:
    build: ./image-metadata
    container_name: image-metadata
    ports:
      - "5001:5000"

  recipes:
    build: ./recipes
    container_name: recipes_service
    ports:
      - "5002:5000"