version: '3.8'

services:
  weather-api:
    build: ./app
    container_name: weather-notes-api
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: unless-stopped